In [2]:
import numpy as np
print(np.__version__)

1.24.3


In [9]:
# 1-D Arrays
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [8]:
# 0-D Arrays
a = np.array(42)
print(a)

42


In [10]:
# 2-D Arrays
b = np.array([
    [1, 2, 3], 
    [4, 5, 6]
])
b


array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
# 3-D Arrays
c = np.array([
    [[1, 2, 3], 
     [4, 5, 6]], 
    [[1, 2, 3], 
     [4, 5, 6]]
])
c

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [14]:
# Define the number of dimensions in an array
d = np.array([1, 2, 3, 4], ndmin = 5)
print(d)
print(d.ndim)

[[[[[1 2 3 4]]]]]
5


#### NumPy Array Indexing

In [6]:
arr_1d = np.array([1, 2, 3, 4])

arr_2d = np.array([[1,2,3,4,5], 
                   [6,7,8,9,10]])

arr_3d = np.array([[[1, 2, 3], 
                    [4, 5, 6]], 
                   [[7, 8, 9], 
                    [10, 11, 12]]])

In [16]:
# array[x, y, z]
print(arr_1d[0])
print(arr_1d[1])
print("=========")

print(arr_2d[0, 1])
print(arr_2d[1, 4])
print("=========")

print(arr_3d[0, 1, 2])
print(arr_3d[1, 1, 2])

1
2
2
10
6
12


In [10]:
def PrintName (fname, lname): 
    print(fname, lname)

In [1]:
import pandas as pd

In [4]:
data30 = pd.read_csv("30.csv")
data90 = pd.read_csv("90.csv")

In [9]:
data30

Hotline                             Column Name              Column Group  \
0   1830830                        ROOM_RESERVATION                       NaN   
1   1830830                            PARK_TICKETS                       NaN   
2   1830830                      DINING_RESERVATION                       NaN   
3   1830830                    MAGIC_ACCESS_MEMBERS                       NaN   
4   1830830                     GENERAL_INFORMATION                       NaN   
5   1830830                          NEWRESERVATION          ROOM_RESERVATION   
6   1830830                   RESERVATION_AMENDMENT          ROOM_RESERVATION   
7   1830830                RESERVATION_CANCELLATION          ROOM_RESERVATION   
8   1830830                  _1DAY2DAY_TICKET_PRICE              PARK_TICKETS   
9   1830830                    PARK_TICKETS_ENQUIRY              PARK_TICKETS   
10  1830830                    MAGIC_ACCESS_RENEWAL      MAGIC_ACCESS_MEMBERS   
11  1830830                                BENEFITS      MAGIC_ACCESS_MEMBERS   
12  1830830                      EVENT_AND_ACTIVITY      MAGIC_ACCESS_MEMBERS   
13  1830830                              PARK_HOURS       GENERAL_INFORMATION   
14  1830830  PARK_LUGGAGE_VALET_SERVICES_AND_LOCKER       GENERAL_INFORMATION   
15  1830830                         STROLLER_RENTAL       GENERAL_INFORMATION   
16  1830830                      WHEEL_CHAIR_RENTAL       GENERAL_INFORMATION   
17  1830830                                    ILRC       GENERAL_INFORMATION   
18  1830830                                 RCC_CAN          ROOM_RESERVATION   
19  1830830                                 RCC_ENG          ROOM_RESERVATION   
20  1830830                                 RCC_PUT          ROOM_RESERVATION   
21  1830830              AMENDMENT_OFFICIAL_CHANNEL     RESERVATION_AMENDMENT   
22  1830830                AMENDMENT_OTHERS_CHANNEL     RESERVATION_AMENDMENT   
23  1830830           CANCELLATION_OFFICIAL_CHANNEL  RESERVATION_CANCELLATION   
24  1830830             CANCELLATION_OTHERS_CHANNEL  RESERVATION_CANCELLATION   
25  1830830                             OPENINGTIME                      ILRC   
26  1830830                              FACILITIES                      ILRC   
27  1830830                          TRANSPORTATION                      ILRC   

    IVRS LEVEL  
0            2  
1            2  
2            2  
3            2  
4            2  
5            3  
6            3  
7            3  
8            3  
9            3  
10           3  
11           3  
12           3  
13           3  
14           3  
15           3  
16           3  
17           3  
18           3  
19           3  
20           3  
21           4  
22           4  
23           4  
24           4  
25           4  
26           4  
27           4

In [22]:
top_level30 = data30[data30['IVRS LEVEL'] == 2]['Column Name']
levels = {'level2': [], 'level3': [], 'level4': []}

for child in top_level30:
    level2 = child
    level3 = data30.loc[data30['Column Group'] == level2, 'Column Name'].tolist()
    
    if level3:
        for l3 in level3:
            level4 = data30.loc[data30['Column Group'] == l3, 'Column Name'].tolist()
            if level4:
                for l4 in level4:
                    levels['level2'].append(level2)
                    levels['level3'].append(l3)
                    levels['level4'].append(l4)
            else:
                levels['level2'].append(level2)
                levels['level3'].append(l3)
                levels['level4'].append(None)
    else:
        levels['level2'].append(level2)
        levels['level3'].append(None)
        levels['level4'].append(None)

result_df = pd.DataFrame(levels)
result_df

result_df.insert(0, 'Hotline', 1830830)
result_df


Hotline                level2                                  level3  \
0   1830830      ROOM_RESERVATION                          NEWRESERVATION   
1   1830830      ROOM_RESERVATION                   RESERVATION_AMENDMENT   
2   1830830      ROOM_RESERVATION                   RESERVATION_AMENDMENT   
3   1830830      ROOM_RESERVATION                RESERVATION_CANCELLATION   
4   1830830      ROOM_RESERVATION                RESERVATION_CANCELLATION   
5   1830830      ROOM_RESERVATION                                 RCC_CAN   
6   1830830      ROOM_RESERVATION                                 RCC_ENG   
7   1830830      ROOM_RESERVATION                                 RCC_PUT   
8   1830830          PARK_TICKETS                  _1DAY2DAY_TICKET_PRICE   
9   1830830          PARK_TICKETS                    PARK_TICKETS_ENQUIRY   
10  1830830    DINING_RESERVATION                                    None   
11  1830830  MAGIC_ACCESS_MEMBERS                    MAGIC_ACCESS_RENEWAL   
12  1830830  MAGIC_ACCESS_MEMBERS                                BENEFITS   
13  1830830  MAGIC_ACCESS_MEMBERS                      EVENT_AND_ACTIVITY   
14  1830830   GENERAL_INFORMATION                              PARK_HOURS   
15  1830830   GENERAL_INFORMATION  PARK_LUGGAGE_VALET_SERVICES_AND_LOCKER   
16  1830830   GENERAL_INFORMATION                         STROLLER_RENTAL   
17  1830830   GENERAL_INFORMATION                      WHEEL_CHAIR_RENTAL   
18  1830830   GENERAL_INFORMATION                                    ILRC   
19  1830830   GENERAL_INFORMATION                                    ILRC   
20  1830830   GENERAL_INFORMATION                                    ILRC   

                           level4  
0                            None  
1      AMENDMENT_OFFICIAL_CHANNEL  
2        AMENDMENT_OTHERS_CHANNEL  
3   CANCELLATION_OFFICIAL_CHANNEL  
4     CANCELLATION_OTHERS_CHANNEL  
5                            None  
6                            None  
7                            None  
8                            None  
9                            None  
10                           None  
11                           None  
12                           None  
13                           None  
14                           None  
15                           None  
16                           None  
17                           None  
18                    OPENINGTIME  
19                     FACILITIES  
20                 TRANSPORTATION

In [6]:
data = {
    'Parent': ['A', 'A', 'B', 'B', 'C', 'D'],
    'Child': ['B', 'C', 'D', 'E', 'F', 'G']
}
df = pd.DataFrame(data)
df

Parent Child
0      A     B
1      A     C
2      B     D
3      B     E
4      C     F
5      D     G

In [15]:
import pandas as pd

# Sample data for illustration
# Replace this with your actual dataset
data = {'Parent': ['A', 'A', 'B', 'B', 'C', 'C', 'D', 'D'], 
        'Child': ['B', 'C', 'D', 'E', 'F', 'G', 'H', 'I']}

df = pd.DataFrame(data)

# Find level2 elements (children with no parents)
level2_items = set(df['Child']) - set(df['Parent'])
level2_items

{'E', 'F', 'G', 'H', 'I'}

In [27]:
Dt = 2.4
gs = 0.1
gl = 0.03
n = 10
r = 0.08

# sum1 = 
# sum2 = 

# E_Stn = 


In [29]:
def expected_share_price(Dt, gs, gl, n, r): 
    sum_short = 0
    for i in range(1, n + 1):
        sum_short += (Dt * (1 + gs) ** i) / ((1 + r)**i)
        print(sum_short)
    E_Stn = ((Dt * ((1 + gs)**n) * (1 + gl))/(r - gl)) * (1 + r)**(-n)
    print(E_Stn)

    print("Result", sum_short + E_Stn)

In [30]:
expected_share_price(3.5, 0.05, 0.03, 20, 0.15)

3.195652173913044
6.113421550094519
8.7774718500863
11.20986560225271
13.430746854230737
15.458507997341108
17.30994208452884
19.000381903265463
20.543826955155424
21.953059393837563
23.239749881329953
24.414554239475176
25.48720169691212
26.466575462398026
27.36078629175472
28.177239657689096
28.92269707875961
29.603332115389215
30.22478149665972
30.792191801298006
4.870271781478642
Result 35.662463582776645
